import * as t from "babel-types";
import { stripIndent } from "common-tags";
import generate from "babel-generator";

export default function buildIdMappingsFile(mappings) {
  const outputContent = t.expressionStatement(
    t.assignmentExpression(
      "=",
      t.memberExpression(t.identifier("module"), t.identifier("exports")),
      t.objectExpression(
        Object.keys(mappings).map((key) => {
          const valueNode = mappings[key];
          const keyNode = t.stringLiteral(key);

          return t.objectProperty(keyNode, valueNode);
        })
      )
    )
  );

  const comment =
    "\n" +
    stripIndent`
      This file was generated by the run-on-server babel plugin. It should not
      be edited by hand.
    ` +
    "\n";

  const output = generate(t.program([outputContent]), {
    auxiliaryCommentBefore: comment,
  });

  return output.code;
}
